---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yooks.
--- DateTime: 1/6/2021 12:10 AM
---

---@class ZombiePacket : zombie.network.packets.ZombiePacket
---@class LuaCompilerTest.String : io.yooksi.pz.zdoc.compile.LuaCompilerTest.String
---@class LuaAnnotator

---@class ArrayList : java.util.ArrayList
---@generic T : java.lang.Object
---@generic v : java.lang.Object


---@class AttackState : zombie.ai.states.AttackState
AttackState = {}

---@class IsoGameCharacter : zombie.characters.IsoGameCharacter

ZomboidLuaDocTest:method(nil, nil)