---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yooks.
--- DateTime: 1/5/2021 11:56 PM
---

---@class Unknown : java.lang.Object
Unknown = {}

---@class Object:java.lang.Object

---@class ZomboidLuaDocTest:io.yooksi.pz.zdoc.doc.ZomboidLuaDocTest
---@field public object Object[]
ZomboidLuaDocTest = {}

---abcd
---
---efeg
---@public
---@param param string|number|boolean
---@param param2 ZomboidLuaDocTest
---@return any | string
function ZomboidLuaDocTest:method(param,param2)
	local a = param2.object[1];

end

local a = ZomboidLuaDocTest.object[i]